import type {
  EvaluationRequest,
  PipelineEvent,
  PluginCapabilities,
  PluginFinding,
  PluginRunRecord,
} from "@openleash/shared";
import { pluginRun } from "../types.js";
import { codeScannerManifest } from "./manifest.js";

const MAX_CODE_CHARS = 30_000;

export type CodeScannerVulnerability = {
  title: string;
  severity: "low" | "medium" | "high" | "critical";
  cwe?: string;
  evidence?: string;
  remediation: string;
};

export type CodeScannerAssessment = {
  risky: boolean;
  riskScore: number;
  severity: "none" | "low" | "medium" | "high" | "critical";
  summary: string;
  vulnerabilities: CodeScannerVulnerability[];
};

export const CODE_SCANNER_SYSTEM_PROMPT = [
  "You are OpenLeash code-scanner, a strict application-security reviewer for code generated by AI coding agents.",
  "Find concrete, exploitable security vulnerabilities in the supplied generated code or patch.",
  "Check injection, broken authentication or authorization, secret exposure, unsafe deserialization, path traversal, SSRF, XSS, CSRF, SQL injection, command execution, insecure cryptography, race conditions, supply-chain risk, unsafe file permissions, and dangerous defaults.",
  "Write every title, summary, and remediation for a person who is new to coding. Explain what could happen in plain language before using any security term or acronym. Never use an acronym such as SSRF, CSRF, XSS, or CWE as the whole title or explanation.",
  "Good example: 'A visitor could make the app send a request somewhere private (often called SSRF).' Bad example: 'SSRF vulnerability.'",
  "Do not report style, maintainability, missing tests, hypothetical concerns without evidence, or vulnerabilities outside the supplied code.",
  "Set risky=true only for a concrete vulnerability. Use riskScore 0-100 and severity none, low, medium, high, or critical.",
  "Evidence must be a short excerpt from the supplied code. Remediation must be specific and actionable.",
  "Return only JSON matching the provided schema.",
].join(" ");

export const CODE_SCANNER_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["risky", "riskScore", "severity", "summary", "vulnerabilities"],
  properties: {
    risky: { type: "boolean" },
    riskScore: { type: "number", minimum: 0, maximum: 100 },
    severity: { enum: ["none", "low", "medium", "high", "critical"] },
    summary: { type: "string" },
    vulnerabilities: {
      type: "array",
      maxItems: 8,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["title", "severity", "remediation"],
        properties: {
          title: { type: "string" },
          severity: { enum: ["low", "medium", "high", "critical"] },
          cwe: { type: "string" },
          evidence: { type: "string" },
          remediation: { type: "string" },
        },
      },
    },
  },
};

export async function runCodeScanner(
  request: EvaluationRequest,
  event: PipelineEvent,
  capabilities: PluginCapabilities,
  config: Record<string, unknown> = {},
): Promise<PluginRunRecord> {
  const startedAt = Date.now();
  const minimumCodeCharacters = clamp(
    Number(config.minimumCodeCharacters ?? 80),
    40,
    4000,
  );
  const candidate = generatedCodeCandidate(request, minimumCodeCharacters);
  if (!candidate) {
    return pluginRun({
      pluginId: codeScannerManifest.id,
      event,
      status: "skipped",
      summary: "No generated code was present in this coding-agent event.",
      startedAt,
      metadata: { agentKind: request.agent.kind, reason: "no-code" },
    });
  }

  const remoteEvaluation = await capabilities.llm.evaluateJson<CodeScannerAssessment>(
    {
      purpose: "code-scanner",
      system: CODE_SCANNER_SYSTEM_PROMPT,
      prompt: JSON.stringify({
        task: "Evaluate this AI-generated code for concrete security vulnerabilities.",
        agentKind: request.agent.kind,
        agentName: request.agent.displayName,
        event,
        source: candidate.source,
        projectPath: request.event.projectPath,
        languageHint: candidate.languageHint,
        code: candidate.code,
      }),
      schema: CODE_SCANNER_SCHEMA,
      temperature: 0,
      maxOutputTokens: 1400,
    },
  ).catch(() => undefined);
  const evaluation = remoteEvaluation ?? {
    json: heuristicCodeAssessment(candidate.code),
    model: "code-scanner-heuristic",
    provider: "openleash-plugin",
    source: "heuristic" as const,
  };

  const assessment = normalizeAssessment(evaluation.json);
  const threshold = clamp(
    Number(config.notificationRiskThreshold ?? 70),
    0,
    100,
  );
  const risky =
    assessment.risky &&
    assessment.riskScore >= threshold &&
    assessment.vulnerabilities.length > 0;
  const findings: PluginFinding[] = assessment.vulnerabilities.map((item) => ({
    title: item.title,
    severity: item.severity,
    summary: item.remediation,
    evidence: item.evidence ? [item.evidence] : undefined,
  }));

  await capabilities.log.emit({
    level: risky ? "security" : "info",
    category: risky ? "security" : "plugin",
    code: risky ? "code-scanner.risky-code" : "code-scanner.code-reviewed",
    message: risky
      ? "Code-scanner found vulnerabilities in AI-generated code."
      : "Code-scanner reviewed AI-generated code without a notification-level finding.",
    data: {
      agentKind: request.agent.kind,
      source: candidate.source,
      riskScore: assessment.riskScore,
      severity: assessment.severity,
      summary: assessment.summary,
      vulnerabilities: assessment.vulnerabilities,
      model: evaluation.model,
      provider: evaluation.provider,
    },
  });

  if (risky) {
    const primary = assessment.vulnerabilities[0];
    await Promise.all([
      capabilities.signals.emit({
        kind: "security.finding",
        severity:
          assessment.severity === "none" ? "medium" : assessment.severity,
        title: "Risky AI-generated code",
        summary: assessment.summary,
        decision: "observed",
        status: "needs_review",
        target: { type: "generated_code", name: request.agent.displayName },
        evidence: assessment.vulnerabilities,
        details: {
          riskScore: assessment.riskScore,
          source: candidate.source,
          agentKind: request.agent.kind,
        },
        correlationKeys: [
          `agent:${request.agent.kind}`,
          `session:${request.event.sessionId}`,
          "code-scanner",
        ],
      }),
      capabilities.notification.send({
        level: assessment.severity === "critical" ? "critical" : "warning",
        title: "Risky code generated",
        summary: `${request.agent.displayName}: ${primary?.title ?? assessment.summary}. ${primary?.remediation ?? "Review the generated code before using it."}`,
        dedupeKey: `code-scanner:${request.agent.kind}:${request.event.sessionId}:${primary?.title ?? assessment.riskScore}`,
        scope: {
          agentKind: request.agent.kind,
          sessionId: request.event.sessionId,
          projectPath: request.event.projectPath,
        },
        minIntervalSeconds: 300,
      }),
    ]);
  }

  return pluginRun({
    pluginId: codeScannerManifest.id,
    event,
    status: "passed",
    summary: risky
      ? `Risky generated code detected (${assessment.riskScore}/100). User notified.`
      : `Generated code reviewed (${assessment.riskScore}/100).`,
    startedAt,
    findings,
    metadata: {
      agentKind: request.agent.kind,
      source: candidate.source,
      riskScore: assessment.riskScore,
      severity: assessment.severity,
      notificationSent: risky,
      evaluatedBy: `${evaluation.provider}:${evaluation.model}`,
    },
  });
}

export function generatedCodeCandidate(
  request: EvaluationRequest,
  minimumCharacters = 80,
) {
  const tool = request.event.tool;
  if (
    tool &&
    /(?:write|edit|patch|notebook|create|replace|insert)/i.test(tool.name)
  ) {
    const code = codeFromToolInput(tool.input);
    if (looksLikeCode(code, minimumCharacters))
      return {
        code: truncate(code, MAX_CODE_CHARS),
        source: `tool:${tool.name}`,
        languageHint: languageHint(code),
      };
  }
  const assistant =
    [...(request.event.transcript ?? [])]
      .reverse()
      .find((turn) => turn.role === "assistant")?.content ?? "";
  const fenced = [...assistant.matchAll(/```([^\n`]*)\n([\s\S]*?)```/g)]
    .map((match) => match[2])
    .join("\n\n");
  const code = fenced || assistant;
  if (!looksLikeCode(code, minimumCharacters)) return undefined;
  return {
    code: truncate(code, MAX_CODE_CHARS),
    source: fenced ? "assistant-code-fence" : "assistant-response",
    languageHint: languageHint(fenced ? assistant : code),
  };
}

function codeFromToolInput(input: unknown): string {
  if (typeof input === "string") return input;
  if (!input || typeof input !== "object") return "";
  const record = input as Record<string, unknown>;
  return [
    "content",
    "code",
    "patch",
    "diff",
    "new_string",
    "newText",
    "text",
    "command",
  ]
    .map((key) => record[key])
    .filter((value): value is string => typeof value === "string")
    .join("\n");
}

function looksLikeCode(value: string, minimumCharacters: number) {
  if (value.trim().length < minimumCharacters) return false;
  const markers = [
    /[{};]\s*(?:\n|$)/,
    /\b(?:function|class|const|let|var|def|import|from|SELECT|INSERT|UPDATE|CREATE)\b/,
    /(?:=>|\bif\s*\(|\bfor\s*\(|\breturn\b)/,
    /^\s*(?:diff --git|@@|[+-]{3}\s)/m,
    /<\/?[a-z][^>]*>/i,
  ];
  return markers.filter((pattern) => pattern.test(value)).length >= 2;
}

function normalizeAssessment(
  value: CodeScannerAssessment,
): CodeScannerAssessment {
  const vulnerabilities = Array.isArray(value?.vulnerabilities)
    ? value.vulnerabilities.slice(0, 8).flatMap((item) => {
        const title = truncate(String(item?.title ?? "").trim(), 160);
        const remediation = truncate(
          String(item?.remediation ?? "").trim(),
          400,
        );
        if (
          !title ||
          !remediation ||
          !["low", "medium", "high", "critical"].includes(item.severity)
        )
          return [];
        return [
          {
            title,
            remediation,
            severity: item.severity,
            cwe: item.cwe ? truncate(String(item.cwe), 40) : undefined,
            evidence: item.evidence
              ? truncate(String(item.evidence), 500)
              : undefined,
          },
        ];
      })
    : [];
  const riskScore = clamp(Number(value?.riskScore ?? 0), 0, 100);
  const severity = ["none", "low", "medium", "high", "critical"].includes(
    value?.severity,
  )
    ? value.severity
    : "none";
  return {
    risky: Boolean(value?.risky && vulnerabilities.length),
    riskScore,
    severity,
    summary: truncate(String(value?.summary ?? "Code review completed."), 400),
    vulnerabilities,
  };
}

function heuristicCodeAssessment(code: string): CodeScannerAssessment {
  const vulnerabilities: CodeScannerVulnerability[] = [];
  const add = (finding: CodeScannerVulnerability) => {
    if (!vulnerabilities.some((item) => item.title === finding.title)) vulnerabilities.push(finding);
  };
  const commandInjection = code.match(/\b(?:eval|exec|execSync|system|popen)\s*\([^\n)]*(?:req\.|request\.|user|input|params|query|body|argv|\$\{)/i);
  if (commandInjection) add({
    title: "User-controlled text can reach executable code",
    severity: "critical",
    cwe: "CWE-78",
    evidence: commandInjection[0],
    remediation: "Use a fixed executable and pass validated values as an argument array without a shell.",
  });
  const sqlInjection = code.match(/\b(?:query|execute)\s*\(\s*(?:`[^`]*\$\{|[^\n)]*\+\s*(?:req\.|request\.|user|input|params|query|body))/i);
  if (sqlInjection) add({
    title: "User input is joined directly into a database query",
    severity: "high",
    cwe: "CWE-89",
    evidence: sqlInjection[0],
    remediation: "Use parameterized queries and pass user values separately from the SQL text.",
  });
  const unsafeHtml = code.match(/\b(?:innerHTML|outerHTML)\s*=\s*(?:req\.|request\.|user|input|params|query|body|[^;\n]*\$\{)/i);
  if (unsafeHtml) add({
    title: "Untrusted text can become executable page content",
    severity: "high",
    cwe: "CWE-79",
    evidence: unsafeHtml[0],
    remediation: "Render untrusted values as text or sanitize them with a maintained HTML sanitizer.",
  });
  const embeddedCredential = code.match(/\b(?:api[_-]?key|secret|password|token)\s*[:=]\s*["'][A-Za-z0-9_=-]{16,}["']/i);
  if (embeddedCredential) add({
    title: "A credential is embedded in generated source code",
    severity: "high",
    cwe: "CWE-798",
    evidence: embeddedCredential[0].replace(/(["']).+\1$/, "$1[REDACTED]$1"),
    remediation: "Remove the value from source control and load it from a protected secret store at runtime.",
  });
  const score = vulnerabilities.some((item) => item.severity === "critical") ? 95 : vulnerabilities.length ? 85 : 0;
  return {
    risky: vulnerabilities.length > 0,
    riskScore: score,
    severity: vulnerabilities.some((item) => item.severity === "critical") ? "critical" : vulnerabilities.length ? "high" : "none",
    summary: vulnerabilities.length
      ? "Deterministic checks found a concrete security risk in generated code."
      : "Deterministic checks found no concrete vulnerability.",
    vulnerabilities,
  };
}

function languageHint(value: string) {
  return value.match(/```([a-zA-Z0-9+#.-]+)/)?.[1] ?? "unknown";
}

function truncate(value: string, max: number) {
  return value.length <= max ? value : `${value.slice(0, max - 3)}...`;
}

function clamp(value: number, min: number, max: number) {
  return Number.isFinite(value)
    ? Math.max(min, Math.min(max, Math.round(value)))
    : min;
}
