substitutions:
  _REGION: us-central1
  _REPOSITORY: leash
  _IMAGE: provider-sync-worker

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - apps/provider-sync-worker/Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}
      - apps/provider-sync-worker
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY
