apiVersion: apps/v1
kind: Deployment
metadata:
  name: openleash-cloud-client-api
spec:
  template:
    spec:
      containers:
        - name: cloud-client-api
          env:
            - name: OPENLEASH_PLUGIN_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: openleash-plugin-runtime
                  key: OPENLEASH_PLUGIN_ENDPOINTS
            - name: OPENLEASH_PLUGIN_RUNTIME_SECRET
              valueFrom:
                secretKeyRef:
                  name: openleash-plugin-runtime
                  key: shared-secret
